In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns

In [18]:
df = pd.read_csv('/Users/rebeccadillon/git/dublin-bus-team-5/data/merged files/merged_weather_trips.csv', parse_dates=['DAYOFSERVICE'])

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 713933 entries, 0 to 713932
Data columns (total 27 columns):
 #   Column               Non-Null Count   Dtype         
---  ------               --------------   -----         
 0   temp                 713933 non-null  float64       
 1   dew_point            713933 non-null  float64       
 2   feels_like           713933 non-null  float64       
 3   temp_min             713933 non-null  float64       
 4   temp_max             713933 non-null  float64       
 5   pressure             713933 non-null  int64         
 6   humidity             713933 non-null  int64         
 7   wind_speed           713933 non-null  float64       
 8   wind_deg             713933 non-null  int64         
 9   rain_1h              713933 non-null  float64       
 10  snow_1h              713933 non-null  float64       
 11  clouds_all           713933 non-null  int64         
 12  weather_id           713933 non-null  int64         
 13  weather_main  

In [20]:
df['TRIPTIME'] = df['ACTUALTIME_ARR']-df['ACTUALTIME_DEP']

Create weekday column

In [21]:
# create weekday column
df['WEEKDAY'] = df['DAYOFSERVICE'].dt.weekday

In [22]:
df['WEEKDAY'].unique()

array([1, 2, 3, 4, 5, 0, 6])

Create month column

In [23]:
df['MONTH'] = df['DAYOFSERVICE'].dt.month
df['MONTH'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
df.head()

temp  dew_point  feels_like  temp_min  temp_max  pressure  humidity  \
0  4.39       0.35        0.25      3.53      4.41      1008        75   
1  5.39       1.32        1.78      5.37      7.57      1004        75   
2  5.39       1.32        1.78      5.37      7.57      1004        75   
3  5.39       1.32        1.78      5.37      7.57      1004        75   
4  5.39       2.40        2.90      5.37      7.57      1003        81   

   wind_speed  wind_deg  rain_1h  ...  LINEID  ROUTEID  DIRECTION  \
0         5.7       240     0.00  ...      65    65_75          2   
1         5.1       150     0.13  ...      65    65_73          1   
2         5.1       150     0.13  ...      40    40_31          2   
3         5.1       150     0.13  ...      40    40_31          2   
4         3.1       160     0.43  ...      14    14_15          1   

  PLANNEDTIME_ARR PLANNEDTIME_DEP  ACTUALTIME_ARR  ACTUALTIME_DEP TRIPTIME  \
0         91213.0         87300.0         90458.0         87314.0   3144.0   
1         23878.0         19800.0         24834.0         20409.0   4425.0   
2         26069.0         21600.0         26163.0         21589.0   4574.0   
3         25469.0         21000.0         25110.0         21004.0   4106.0   
4         26508.0         22500.0         26011.0         22497.0   3514.0   

   WEEKDAY  MONTH  
0        1      1  
1        1      1  
2        1      1  
3        1      1  
4        1      1  

[5 rows x 30 columns]

Create rushhour column with values 0 (hours outside of rushour) and 1 (values inside rushhour i.e., hour value of 6-9 and 15-18)

In [25]:
df['HOUR'].unique()

array([ 0,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23,  4])

In [26]:
# code from https://stackoverflow.com/questions/70755998/dataframe-isin-for-integers

condition_rushhour = df['HOUR'].isin([6,7,8,9,15,16,17,18])
df['RUSHHOUR'] = (condition_rushhour).astype(int)

In [27]:
df

temp  dew_point  feels_like  temp_min  temp_max  pressure  humidity  \
0       4.39       0.35        0.25      3.53      4.41      1008        75   
1       5.39       1.32        1.78      5.37      7.57      1004        75   
2       5.39       1.32        1.78      5.37      7.57      1004        75   
3       5.39       1.32        1.78      5.37      7.57      1004        75   
4       5.39       2.40        2.90      5.37      7.57      1003        81   
...      ...        ...         ...       ...       ...       ...       ...   
713928  9.76       6.48        9.09      9.27     10.32      1034        80   
713929  9.76       6.48        9.09      9.27     10.32      1034        80   
713930  9.76       6.48        9.09      9.27     10.32      1034        80   
713931  9.76       6.48        9.09      9.27     10.32      1034        80   
713932  9.76       6.48        9.09      9.27     10.32      1034        80   

        wind_speed  wind_deg  rain_1h  ...  ROUTEID  DIRECTION  \
0             5.70       240     0.00  ...    65_75          2   
1             5.10       150     0.13  ...    65_73          1   
2             5.10       150     0.13  ...    40_31          2   
3             5.10       150     0.13  ...    40_31          2   
4             3.10       160     0.43  ...    14_15          1   
...            ...       ...      ...  ...      ...        ...   
713928        1.79       282     0.00  ...   120_12          1   
713929        1.79       282     0.00  ...   27B_34          2   
713930        1.79       282     0.00  ...    32_58          2   
713931        1.79       282     0.00  ...  25A_273          1   
713932        1.79       282     0.00  ...  40D_103          2   

        PLANNEDTIME_ARR PLANNEDTIME_DEP ACTUALTIME_ARR  ACTUALTIME_DEP  \
0               91213.0         87300.0        90458.0         87314.0   
1               23878.0         19800.0        24834.0         20409.0   
2               26069.0         21600.0        26163.0         21589.0   
3               25469.0         21000.0        25110.0         21004.0   
4               26508.0         22500.0        26011.0         22497.0   
...                 ...             ...            ...             ...   
713928          80376.0         79200.0        80529.0         79202.0   
713929          81049.0         78900.0        81634.0         79246.0   
713930          81987.0         80100.0        81577.0         79482.0   
713931          81636.0         79320.0        81983.0         79238.0   
713932          79826.0         78000.0        81512.0         79204.0   

        TRIPTIME WEEKDAY  MONTH  RUSHHOUR  
0         3144.0       1      1         0  
1         4425.0       1      1         0  
2         4574.0       1      1         0  
3         4106.0       1      1         0  
4         3514.0       1      1         1  
...          ...     ...    ...       ...  
713928    1327.0       0     12         0  
713929    2388.0       0     12         0  
713930    2095.0       0     12         0  
713931    2745.0       0     12         0  
713932    2308.0       0     12         0  

[713933 rows x 31 columns]

#### Drop unnecessary columns
We can now drop the following columns from the dataframe as they provide no additional information or the information required has been extracted from them.
* DAYOFSERVICE
* PLANNEDTIME_ARR
* PLANNEDTIME_DEP
* ACTUALTIME_ARR
* ACTUALTIME_DEP

In [28]:
# drop unnecessary columns
df.drop(columns=['DAYOFSERVICE','PLANNEDTIME_ARR','PLANNEDTIME_DEP','ACTUALTIME_ARR','ACTUALTIME_DEP'], inplace=True)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 713933 entries, 0 to 713932
Data columns (total 26 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   temp                 713933 non-null  float64
 1   dew_point            713933 non-null  float64
 2   feels_like           713933 non-null  float64
 3   temp_min             713933 non-null  float64
 4   temp_max             713933 non-null  float64
 5   pressure             713933 non-null  int64  
 6   humidity             713933 non-null  int64  
 7   wind_speed           713933 non-null  float64
 8   wind_deg             713933 non-null  int64  
 9   rain_1h              713933 non-null  float64
 10  snow_1h              713933 non-null  float64
 11  clouds_all           713933 non-null  int64  
 12  weather_id           713933 non-null  int64  
 13  weather_main         713933 non-null  object 
 14  weather_description  713933 non-null  object 
 15  snow_ice         

## Review and prep

In [30]:
df.isna().sum()

temp                   0
dew_point              0
feels_like             0
temp_min               0
temp_max               0
pressure               0
humidity               0
wind_speed             0
wind_deg               0
rain_1h                0
snow_1h                0
clouds_all             0
weather_id             0
weather_main           0
weather_description    0
snow_ice               0
heavy_precip           0
HOUR                   0
TRIPID                 0
LINEID                 0
ROUTEID                0
DIRECTION              0
TRIPTIME               0
WEEKDAY                0
MONTH                  0
RUSHHOUR               0
dtype: int64

In [31]:
df.dtypes

temp                   float64
dew_point              float64
feels_like             float64
temp_min               float64
temp_max               float64
pressure                 int64
humidity                 int64
wind_speed             float64
wind_deg                 int64
rain_1h                float64
snow_1h                float64
clouds_all               int64
weather_id               int64
weather_main            object
weather_description     object
snow_ice                 int64
heavy_precip             int64
HOUR                     int64
TRIPID                   int64
LINEID                  object
ROUTEID                 object
DIRECTION                int64
TRIPTIME               float64
WEEKDAY                  int64
MONTH                    int64
RUSHHOUR                 int64
dtype: object

In [32]:
categorical_cols = df.select_dtypes(['object']).columns
categorical_cols = categorical_cols.append(df[['weather_id','snow_ice','heavy_precip','HOUR','TRIPID', 'DIRECTION', 'WEEKDAY', 'MONTH', 'RUSHHOUR']].columns)
# convert columns in the list to categorical columns
for col in categorical_cols:
    df[col] = df[col].astype('category')
df.dtypes

temp                    float64
dew_point               float64
feels_like              float64
temp_min                float64
temp_max                float64
pressure                  int64
humidity                  int64
wind_speed              float64
wind_deg                  int64
rain_1h                 float64
snow_1h                 float64
clouds_all                int64
weather_id             category
weather_main           category
weather_description    category
snow_ice               category
heavy_precip           category
HOUR                   category
TRIPID                 category
LINEID                 category
ROUTEID                category
DIRECTION              category
TRIPTIME                float64
WEEKDAY                category
MONTH                  category
RUSHHOUR               category
dtype: object

In [33]:
df.describe().T 

count         mean          std      min      25%      50%  \
temp        713933.0    11.227679     5.545384    -4.61     7.39    10.89   
dew_point   713933.0     6.970820     4.497444    -7.99     4.22     7.32   
feels_like  713933.0     9.438611     6.973952   -10.61     3.79    10.10   
temp_min    713933.0    10.948935     5.567766    -4.63     7.05    10.37   
temp_max    713933.0    11.814206     5.672440    -3.43     7.57    11.57   
pressure    713933.0  1012.951918    12.149173   979.00  1005.00  1014.00   
humidity    713933.0    76.598301    14.137277    25.00    67.00    77.00   
wind_speed  713933.0     5.342469     2.676054     0.00     3.60     5.10   
wind_deg    713933.0   186.634195    88.785287     0.00   130.00   200.00   
rain_1h     713933.0     0.083846     0.245155     0.00     0.00     0.00   
snow_1h     713933.0     0.000701     0.013219     0.00     0.00     0.00   
clouds_all  713933.0    58.873466    25.220222     0.00    40.00    75.00   
TRIPTIME    713933.0  3838.017465  1431.320354 -7139.00  2789.00  3752.00   

                75%       max  
temp          15.39     26.39  
dew_point     10.24     19.36  
feels_like    14.86     26.39  
temp_min      15.37     26.37  
temp_max      15.57     27.57  
pressure    1022.00   1041.00  
humidity      87.00    100.00  
wind_speed     6.70     18.50  
wind_deg     250.00    360.00  
rain_1h        0.00      3.44  
snow_1h        0.00      0.53  
clouds_all    75.00     90.00  
TRIPTIME    4825.00  17375.00

In [34]:
continuous_cols = df.select_dtypes(['float64', 'int64']).columns

In [35]:
df.duplicated().value_counts()

False    713933
dtype: int64

In [36]:
df.nunique()

temp                      315
dew_point                 632
feels_like                849
temp_min                  186
temp_max                  220
pressure                   63
humidity                   73
wind_speed                 67
wind_deg                  139
rain_1h                   138
snow_1h                    20
clouds_all                  5
weather_id                 20
weather_main                8
weather_description        20
snow_ice                    2
heavy_precip                2
HOUR                       21
TRIPID                 358392
LINEID                    130
ROUTEID                   583
DIRECTION                   2
TRIPTIME                 8666
WEEKDAY                     7
MONTH                      12
RUSHHOUR                    2
dtype: int64

In [37]:
# check logical integrity of data
# Check for negative triptimes
negative_triptimes = list(df[df['TRIPTIME']<0]['TRIPID'])
len(negative_triptimes)

43

In [38]:
df = df.drop(df[df['TRIPTIME']<0].index)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 713890 entries, 0 to 713932
Data columns (total 26 columns):
 #   Column               Non-Null Count   Dtype   
---  ------               --------------   -----   
 0   temp                 713890 non-null  float64 
 1   dew_point            713890 non-null  float64 
 2   feels_like           713890 non-null  float64 
 3   temp_min             713890 non-null  float64 
 4   temp_max             713890 non-null  float64 
 5   pressure             713890 non-null  int64   
 6   humidity             713890 non-null  int64   
 7   wind_speed           713890 non-null  float64 
 8   wind_deg             713890 non-null  int64   
 9   rain_1h              713890 non-null  float64 
 10  snow_1h              713890 non-null  float64 
 11  clouds_all           713890 non-null  int64   
 12  weather_id           713890 non-null  category
 13  weather_main         713890 non-null  category
 14  weather_description  713890 non-null  category
 15  

In [40]:
df.to_csv('/Users/rebeccadillon/git/dublin-bus-team-5/data/cleaned/cleaned_merged_weather_trips.csv', index=False)