In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns

In [2]:
df = pd.read_csv('/Users/rebeccadillon/git/dublin-bus-team-5/data/merged files/merged_weather_trips.csv', parse_dates=['DAYOFSERVICE'])

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 688882 entries, 0 to 688881
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype         
---  ------           --------------   -----         
 0   RAIN             688882 non-null  float64       
 1   TEMP             688882 non-null  float64       
 2   IS_RAINING       688882 non-null  int64         
 3   IS_FREEZING      688882 non-null  int64         
 4   DAYOFSERVICE     688882 non-null  datetime64[ns]
 5   HOUR             688882 non-null  int64         
 6   TRIPID           688882 non-null  int64         
 7   LINEID           688882 non-null  object        
 8   ROUTEID          688882 non-null  object        
 9   DIRECTION        688882 non-null  int64         
 10  PLANNEDTIME_ARR  688882 non-null  float64       
 11  PLANNEDTIME_DEP  688882 non-null  float64       
 12  ACTUALTIME_ARR   688882 non-null  float64       
 13  ACTUALTIME_DEP   688882 non-null  float64       
dtypes: datetime64[ns](1)

In [4]:
df['TRIPTIME'] = df['ACTUALTIME_ARR']-df['ACTUALTIME_DEP']

Create weekday column

In [5]:
# create weekday column
df['WEEKDAY'] = df['DAYOFSERVICE'].dt.weekday

In [6]:
df['WEEKDAY'].unique()

array([1, 2, 3, 4, 5, 0, 6])

Create month column

In [7]:
df['MONTH'] = df['DAYOFSERVICE'].dt.month
df['MONTH'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
df.head()

RAIN  TEMP  IS_RAINING  IS_FREEZING DAYOFSERVICE  HOUR   TRIPID LINEID  \
0   0.0   3.8           0            0   2018-01-02     0  5963431     65   
1   0.0   5.2           0            0   2018-01-02     5  5963422     65   
2   0.0   5.2           0            0   2018-01-02     5  5962263     40   
3   0.0   5.2           0            0   2018-01-02     5  5963304     40   
4   0.5   5.8           1            0   2018-01-02     6  5961178     14   

  ROUTEID  DIRECTION  PLANNEDTIME_ARR  PLANNEDTIME_DEP  ACTUALTIME_ARR  \
0   65_75          2          91213.0          87300.0         90458.0   
1   65_73          1          23878.0          19800.0         24834.0   
2   40_31          2          26069.0          21600.0         26163.0   
3   40_31          2          25469.0          21000.0         25110.0   
4   14_15          1          26508.0          22500.0         26011.0   

   ACTUALTIME_DEP  TRIPTIME  WEEKDAY  MONTH  
0         87314.0    3144.0        1      1  
1         20409.0    4425.0        1      1  
2         21589.0    4574.0        1      1  
3         21004.0    4106.0        1      1  
4         22497.0    3514.0        1      1

Create rushhour column with values 0 (hours outside of rushour) and 1 (values inside rushhour i.e., hour value of 6-9 and 15-18)

In [9]:
df['HOUR'].unique()

array([ 0,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23,  4])

In [10]:
# code from https://stackoverflow.com/questions/70755998/dataframe-isin-for-integers

condition_rushhour = df['HOUR'].isin([6,7,8,9,15,16,17,18])
df['RUSHHOUR'] = (condition_rushhour).astype(int)

In [11]:
df

RAIN  TEMP  IS_RAINING  IS_FREEZING DAYOFSERVICE  HOUR   TRIPID  \
0        0.0   3.8           0            0   2018-01-02     0  5963431   
1        0.0   5.2           0            0   2018-01-02     5  5963422   
2        0.0   5.2           0            0   2018-01-02     5  5962263   
3        0.0   5.2           0            0   2018-01-02     5  5963304   
4        0.5   5.8           1            0   2018-01-02     6  5961178   
...      ...   ...         ...          ...          ...   ...      ...   
688877   0.0   9.9           0            0   2018-12-31    22  8589536   
688878   0.0   9.9           0            0   2018-12-31    22  8586917   
688879   0.0   9.9           0            0   2018-12-31    22  8582081   
688880   0.0   9.9           0            0   2018-12-31    22  8584078   
688881   0.0   9.9           0            0   2018-12-31    22  8589189   

       LINEID  ROUTEID  DIRECTION  PLANNEDTIME_ARR  PLANNEDTIME_DEP  \
0          65    65_75          2          91213.0          87300.0   
1          65    65_73          1          23878.0          19800.0   
2          40    40_31          2          26069.0          21600.0   
3          40    40_31          2          25469.0          21000.0   
4          14    14_15          1          26508.0          22500.0   
...       ...      ...        ...              ...              ...   
688877    120   120_12          1          80376.0          79200.0   
688878    27B   27B_34          2          81049.0          78900.0   
688879     32    32_58          2          81987.0          80100.0   
688880    25A  25A_273          1          81636.0          79320.0   
688881    40D  40D_103          2          79826.0          78000.0   

        ACTUALTIME_ARR  ACTUALTIME_DEP  TRIPTIME  WEEKDAY  MONTH  RUSHHOUR  
0              90458.0         87314.0    3144.0        1      1         0  
1              24834.0         20409.0    4425.0        1      1         0  
2              26163.0         21589.0    4574.0        1      1         0  
3              25110.0         21004.0    4106.0        1      1         0  
4              26011.0         22497.0    3514.0        1      1         1  
...                ...             ...       ...      ...    ...       ...  
688877         80529.0         79202.0    1327.0        0     12         0  
688878         81634.0         79246.0    2388.0        0     12         0  
688879         81577.0         79482.0    2095.0        0     12         0  
688880         81983.0         79238.0    2745.0        0     12         0  
688881         81512.0         79204.0    2308.0        0     12         0  

[688882 rows x 18 columns]

#### Drop unnecessary columns
We can now drop the following columns from the dataframe as they provide no additional information or the information required has been extracted from them.
* DAYOFSERVICE
* PLANNEDTIME_ARR
* PLANNEDTIME_DEP
* ACTUALTIME_ARR
* ACTUALTIME_DEP

In [12]:
# drop unnecessary columns
df.drop(columns=['DAYOFSERVICE','PLANNEDTIME_ARR','PLANNEDTIME_DEP','ACTUALTIME_ARR','ACTUALTIME_DEP'], inplace=True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 688882 entries, 0 to 688881
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   RAIN         688882 non-null  float64
 1   TEMP         688882 non-null  float64
 2   IS_RAINING   688882 non-null  int64  
 3   IS_FREEZING  688882 non-null  int64  
 4   HOUR         688882 non-null  int64  
 5   TRIPID       688882 non-null  int64  
 6   LINEID       688882 non-null  object 
 7   ROUTEID      688882 non-null  object 
 8   DIRECTION    688882 non-null  int64  
 9   TRIPTIME     688882 non-null  float64
 10  WEEKDAY      688882 non-null  int64  
 11  MONTH        688882 non-null  int64  
 12  RUSHHOUR     688882 non-null  int64  
dtypes: float64(3), int64(8), object(2)
memory usage: 68.3+ MB


## Review and prep

In [14]:
df.isna().sum()

RAIN           0
TEMP           0
IS_RAINING     0
IS_FREEZING    0
HOUR           0
TRIPID         0
LINEID         0
ROUTEID        0
DIRECTION      0
TRIPTIME       0
WEEKDAY        0
MONTH          0
RUSHHOUR       0
dtype: int64

In [15]:
df.dtypes

RAIN           float64
TEMP           float64
IS_RAINING       int64
IS_FREEZING      int64
HOUR             int64
TRIPID           int64
LINEID          object
ROUTEID         object
DIRECTION        int64
TRIPTIME       float64
WEEKDAY          int64
MONTH            int64
RUSHHOUR         int64
dtype: object

In [18]:
categorical_cols = df.select_dtypes(['object']).columns
categorical_cols = categorical_cols.append(df[['IS_RAINING','IS_FREEZING','HOUR','TRIPID', 'DIRECTION', 'WEEKDAY', 'MONTH', 'RUSHHOUR']].columns)
# convert columns in the list to categorical columns
for col in categorical_cols:
    df[col] = df[col].astype('category')
df.dtypes

RAIN            float64
TEMP            float64
IS_RAINING     category
IS_FREEZING    category
HOUR           category
TRIPID         category
LINEID         category
ROUTEID        category
DIRECTION      category
TRIPTIME        float64
WEEKDAY        category
MONTH          category
RUSHHOUR       category
dtype: object

In [19]:
df.describe().T 

count         mean          std     min     25%     50%     75%  \
RAIN      688882.0     0.053168     0.289991     0.0     0.0     0.0     0.0   
TEMP      688882.0    11.398091     5.763468    -3.0     7.1    11.1    15.7   
TRIPTIME  688882.0  3838.757487  1431.441611 -7139.0  2789.0  3753.0  4826.0   

              max  
RAIN          8.6  
TEMP         27.5  
TRIPTIME  17375.0

In [20]:
continuous_cols = df.select_dtypes(['float64']).columns

In [21]:
df.duplicated().value_counts()

False    688882
dtype: int64

In [22]:
df.nunique()

RAIN               34
TEMP              288
IS_RAINING          2
IS_FREEZING         2
HOUR               21
TRIPID         358406
LINEID            130
ROUTEID           583
DIRECTION           2
TRIPTIME         8666
WEEKDAY             7
MONTH              12
RUSHHOUR            2
dtype: int64

In [23]:
# check logical integrity of data
# Check for negative triptimes
negative_triptimes = list(df[df['TRIPTIME']<0]['TRIPID'])
len(negative_triptimes)

40

In [27]:
df = df.drop(df[df['TRIPTIME']<0].index)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 688842 entries, 0 to 688881
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype   
---  ------       --------------   -----   
 0   RAIN         688842 non-null  float64 
 1   TEMP         688842 non-null  float64 
 2   IS_RAINING   688842 non-null  category
 3   IS_FREEZING  688842 non-null  category
 4   HOUR         688842 non-null  category
 5   TRIPID       688842 non-null  category
 6   LINEID       688842 non-null  category
 7   ROUTEID      688842 non-null  category
 8   DIRECTION    688842 non-null  category
 9   TRIPTIME     688842 non-null  float64 
 10  WEEKDAY      688842 non-null  category
 11  MONTH        688842 non-null  category
 12  RUSHHOUR     688842 non-null  category
dtypes: category(10), float64(3)
memory usage: 41.7 MB


In [34]:
# reordering the features to make the dataframe more intuitive
df = df[['TRIPID','LINEID','ROUTEID','DIRECTION','WEEKDAY','HOUR','MONTH','TRIPTIME','RUSHHOUR','RAIN','TEMP','IS_RAINING','IS_FREEZING']]

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 688842 entries, 0 to 688881
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype   
---  ------       --------------   -----   
 0   TRIPID       688842 non-null  category
 1   LINEID       688842 non-null  category
 2   ROUTEID      688842 non-null  category
 3   DIRECTION    688842 non-null  category
 4   WEEKDAY      688842 non-null  category
 5   HOUR         688842 non-null  category
 6   MONTH        688842 non-null  category
 7   TRIPTIME     688842 non-null  float64 
 8   RUSHHOUR     688842 non-null  category
 9   RAIN         688842 non-null  float64 
 10  TEMP         688842 non-null  float64 
 11  IS_RAINING   688842 non-null  category
 12  IS_FREEZING  688842 non-null  category
dtypes: category(10), float64(3)
memory usage: 41.7 MB


In [36]:
df.to_csv('cleaned_merged_weather_trips.csv', index=False)